### ISSUE TITLE
Snapshot generator doesn't seem to be working

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3446]
This is the error we're seeing in the logs:

```
[main-actor-system-akka.actor.default-dispatcher-2] [akka://main-actor-system/user/$a] Message [com.sksamuel.elastic4s.streams.PublishActor$Request] from Actor[akka://main-actor-system/user/$a#-872246242] to Actor[akka://main-actor-system/user/$a#-872246242] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://main-actor-system/user/$a#-872246242]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[main-actor-system-akka.actor.default-dispatcher-10] ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: java.nio.channels.CancelledKeyException
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.nio.channels.CancelledKeyException
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
    at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
    at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
    at org.elasticsearch.client.RestClient$1.failed(RestClient.java:567)
    at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:138)
    at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
    at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:143)
    at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:531)
    at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:516)
    at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:250)
    at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:445)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient.send(ElasticsearchJavaRestClient.scala:70)
    at com.sksamuel.elastic4s.http.Executor$$anon$1.exec(Executor.scala:22)
    at com.sksamuel.elastic4s.http.Executor$$anon$1.exec(Executor.scala:15)
    at com.sksamuel.elastic4s.http.ElasticClient.execute(ElasticClient.scala:31)
    at com.sksamuel.elastic4s.streams.PublishActor$$anonfun$com$sksamuel$elastic4s$streams$PublishActor$$ready$1.applyOrElse(ScrollPublisher.scala:121)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at com.sksamuel.elastic4s.streams.PublishActor.aroundReceive(ScrollPublisher.scala:70)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
    at akka.actor.ActorCell.invoke(ActorCell.scala:557)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.channels.CancelledKeyException: null
    at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
    at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
    at org.apache.http.impl.nio.reactor.IOSessionImpl.getEventMask(IOSessionImpl.java:140)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.updateEventMask(SSLIOSession.java:389)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.close(SSLIOSession.java:640)
    at org.apache.http.impl.nio.NHttpConnectionBase.close(NHttpConnectionBase.java:511)
    at org.apache.http.impl.nio.conn.CPoolEntry.closeConnection(CPoolEntry.java:75)
    at org.apache.http.impl.nio.conn.CPoolEntry.close(CPoolEntry.java:101)
    at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:376)
    at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:276)
    at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:266)
    at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:363)
    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:125)
    at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
    ... 21 common frames omitted`
```

A cursory check of ECS config looks sensible, and is pointing at the right ES index + auth. It does appear to get partway through the request (I see some Scroll logs from elastic4s).

**Comment by alexwlchan** [comment]
Oh, and the last V2 snapshot in S3 was updated 29 January.

**Comment by alexwlchan** [comment]
Did a bit of poking around today, got a bit further.

The first issue is that scaling is wonky:

![Screenshot 2019-04-17 at 14 17 40](https://user-images.githubusercontent.com/301220/56290819-e5dd2f00-611b-11e9-91bb-06a4f9170786.png)

If the snapshot generator gets stuck, it will never pick up new messages from the queue and never get restarted by ECS.

Second is that it’s running out of memory when it eventually runs:

```
Exception in thread "I/O dispatcher 1" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOfRange(Arrays.java:3664)
    at java.lang.String.<init>(String.java:207)
    at java.lang.StringBuilder.toString(StringBuilder.java:407)
    at scala.collection.mutable.StringBuilder.toString(StringBuilder.scala:429)
    at scala.collection.mutable.StringBuilder.result(StringBuilder.scala:445)
    at scala.io.BufferedSource.mkString(BufferedSource.scala:97)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient.$anonfun$fromResponse$1(ElasticsearchJavaRestClient.scala:44)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$Lambda$966/1902918929.apply(Unknown Source)
    at scala.Option.map(Option.scala:146)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient.fromResponse(ElasticsearchJavaRestClient.scala:35)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onSuccess(ElasticsearchJavaRestClient.scala:60)
    at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:842)
    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:543)
    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
    at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
```

This suggests that it's trying to read the whole data set into memory, which feels like a mistake.

**Comment by alexwlchan** [comment]
Fixed!
