### ISSUE TITLE
Is the post-replicator verifier a bit too fast?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3897]
This error came through in the Glacier verifier earlier:

```
13:38:17.612 [main-actor-system-akka.actor.default-dispatcher-37] WARN u.a.w.p.a.b.services.BagVerifier - Errors verifying wellcomecollection-storage-replica-ireland/digitised/b30149010/v1:
13:38:17 https://wellcomecollection-storage-replica-ireland.s3.eu-west-1.amazonaws.com/digitised/b30149010/v1/data/alto/b30149010_0013.xml: Location not available!
13:38:17.644 [main-actor-system-akka.actor.default-dispatcher-37] ERROR u.a.w.p.a.c.s.m.IngestStepWorker$$anon$1 - DeterministicFailure(java.lang.Throwable: Unable to verify one file in the bag: data/alto/b30149010_0013.xml,Some(root=wellcomecollection-storage-replica-ireland/digitised/b30149010/v1, status=failure, verified=60, failed=1, ingestId=2c9ecfcd-5072-41dc-8359-e6cd29255d6a, duration=PT1.
java.lang.Throwable: Unable to verify one file in the bag: data/alto/b30149010_0013.xml
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifier.buildStepResult(BagVerifier.scala:403)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifier.$anonfun$verify$1(BagVerifier.scala:90)
at scala.util.Try$.apply(Try.scala:209)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifier.verify(BagVerifier.scala:41)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifierWorker.$anonfun$processMessage$1(BagVerifierWorker.scala:42)
at scala.util.Success.flatMap(Try.scala:247)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifierWorker.processMessage(BagVerifierWorker.scala:38)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifierWorker.processMessage(BagVerifierWorker.scala:19)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.archive.bagverifier.services.BagVerifierWorker.process(BagVerifierWorker.scala:19)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

But if you look in S3, that object exists!

<img width="950" alt="Screenshot 2019-09-12 at 20 15 29" src="https://user-images.githubusercontent.com/301220/64813783-12e22080-d59a-11e9-8029-0179395ec19d.png">

There’s only a 6 second delay between the object being written and us trying to read it – I wonder if we’re being bitten by slow read-after-write consistency, and because we're writing so much to S3 it's just not available yet?

**Comment by alexwlchan** [comment]
Aha, no – it’s because the replicator will do a GetObject first, which kicks us into a different consistency mode. If we went ahead and started writing immediately, we wouldn't hit this issue – but then we wouldn't overwrite existing objects in S3.

**Comment by alexwlchan** [comment]
See https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html

**Comment by alexwlchan** [comment]
This is substantially better now we have scaling in all the parts – the verifier usually doesn't start until several minutes after the replicator, giving time for S3 to catch up.

That doesn't fix the underlying issue, but it means it's less likely to bite us.

**Comment by kenoir** [comment]
>Aha, no – it’s because the replicator will do a GetObject first, which kicks us into a different consistency mode. If we went ahead and started writing immediately, we wouldn't hit this issue – but then we wouldn't overwrite existing objects in S3.

This is a really good "shooting ourselves in the foot" mistake.

**Comment by alexwlchan** [comment]
I'm about to rip a large portion of this code out; leaving a note here for future readers about what we used to do with this code:

```scala
// If we know that there is nothing under the prefix (and we're the only
// replicator writing to it due to the lock), we can skip checking for
// overwrites.
//
// This gives us read-after-write consistency, rather than eventual
// consistency, and makes the verifier more reliable.
//
// See: https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html
//
//      Amazon S3 provides read-after-write consistency for PUTS of new objects
//      in your S3 bucket in all Regions with one caveat. The caveat is that if
//      you make a HEAD or GET request to a key name before the object is created,
//      then create the object shortly after that, a subsequent GET might not
//      return the object due to eventual consistency.
//
// See also: https://github.com/wellcomecollection/platform/issues/3897
//
// In theory this could be even more sophisticated, and compare the keys to
// replicate against a list of existing keys -- but that would make the code
// even more complicated, and it's not clear it would be beneficial.
//
```
