### ISSUE TITLE
If we can't read from a queue, an app hangs forever

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4046]
Spotted in the prod ingests monitor just now:

```
com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.eu-west-1.amazonaws.com/975596993436/storage_prod_ingests_input is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: 777d3293-7457-55cc-a2a6-64acfb8ae49d)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2033)
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2009)
at com.amazonaws.services.sqs.AmazonSQSClient.executeChangeMessageVisibility(AmazonSQSClient.java:520)
at com.amazonaws.services.sqs.AmazonSQSAsyncClient$2.call(AmazonSQSAsyncClient.java:402)
at com.amazonaws.services.sqs.AmazonSQSAsyncClient$2.call(AmazonSQSAsyncClient.java:396)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
15:45:34.418 [main] INFO u.a.w.platform.archive.ingests.Main$ - Terminating worker.
```

When this happens, the app stops processing work, but the ECS task doesn't get terminated, and the work on the queue never gets processed.

We can implement https://github.com/wellcometrust/platform/issues/4014 as a short-term fix, but we should really fix this at the code level. If we can't read from a queue, stop the process and let ECS respawn the task.

**Comment by alexwlchan** [comment]
I think this is fixed by https://github.com/wellcomecollection/scala-libs/pull/76
