### ISSUE TITLE
Bag unpacker is having memory issues unpacking a bag

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4326]
From early afternoon today, the bag unpacker has been having memory issues:

```
Uncaught error from thread [main-actor-system-akka.actor.default-dispatcher-15]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[main-actor-system]
java.lang.OutOfMemoryError: Java heap space
at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:128)
at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:159)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2315)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:765)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader$S3StreamEnumeration.nextElement(S3Unpacker.scala:98)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader$S3StreamEnumeration.nextElement(S3Unpacker.scala:57)
at java.base/java.io.SequenceInputStream.peekNextStream(SequenceInputStream.java:102)
at java.base/java.io.SequenceInputStream.<init>(SequenceInputStream.java:68)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader.$anonfun$get$1(S3Unpacker.scala:137)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader$$Lambda$473/0x00000008405c0440.apply(Unknown Source)
at scala.util.Try$.apply(Try.scala:209)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader.get(S3Unpacker.scala:106)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3StreamReader.get$(S3Unpacker.scala:105)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3Unpacker$$anon$1.get(S3Unpacker.scala:182)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3Unpacker.get(S3Unpacker.scala:189)
at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.unpack(Unpacker.scala:55)
at uk.ac.wellcome.platform.archive.bagunpacker.services.Unpacker.unpack$(Unpacker.scala:46)
at uk.ac.wellcome.platform.archive.bagunpacker.services.s3.S3Unpacker.unpack(S3Unpacker.scala:177)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.$anonfun$processMessage$2(BagUnpackerWorker.scala:52)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker$$Lambda$472/0x00000008405c0840.apply(Unknown Source)
at scala.util.Success.flatMap(Try.scala:247)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.processMessage(BagUnpackerWorker.scala:41)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.processMessage(BagUnpackerWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process(IngestStepResult.scala:78)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker.process$(IngestStepResult.scala:77)
at uk.ac.wellcome.platform.archive.bagunpacker.services.BagUnpackerWorker.process(BagUnpackerWorker.scala:24)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.platform.archive.common.storage.models.IngestStepWorker$$anon$1$$anonfun$$lessinit$greater$1.apply(IngestStepResult.scala:82)
at uk.ac.wellcome.messaging.worker.steps.MessageProcessor.$anonfun$process$1(MessageProcessor.scala:18)
```

It’s fairly generously provisioned; we give it 4GB of space. We could increase that upper limit (and unless I find the issue quickly, that’s what I’ll do) – but given we can handle C&D with nearly 1 million files, I’m a bit surprised any of these bags would cause a problem. Are we leaking something?

These are our currently in-flight ingests:

```
84ae9145-45d7-4f11-afa1-c25a0dd264df | digitised               | b13147006
0822277e-7512-425c-a6d9-c29c0bf01414 | digitised               | b13147444
335d12f4-313b-48a7-8539-8a33860b881f | born-digital-accessions | 2496
d3bdb04f-8431-4b37-a6fb-fc67c74559b6 | digitised               | b13147195
0792f2ed-d1ae-4341-a67f-0c1c2c8a4839 | digitised               | b13147420
```

This is blocking new ingests.

**Comment by alexwlchan** [comment]
The first instance of this was at 13:53, which I think is when I deployed the new unpacker:

* Without warnings about "not read all the bytes from the stream", and
* Without default AWS SDK metrics

It’s happened multiple times since then; presumably when it wakes up and picks a bag off the queue?

**Comment by alexwlchan** [comment]
Judging by timestamps on the ingests, b13147195 appears to be the poison pill – the ingest was created at 13:52; by the time the other bags came along, the unpacker was already having issues.

**Comment by alexwlchan** [comment]
Adding debug logging to the bag unpacker reveals the issue:

```
DEBUG u.a.w.p.a.c.i.services.IngestUpdater - Sending an ingest update for ID=031d5060-7a62-48e7-baaf-0937f8fc9ccc step=IngestStepStarted(031d5060-7a62-48e7-baaf-0937f8fc9ccc)
DEBUG u.a.w.p.a.b.s.s3.S3Unpacker$$anon$1 - Reading wellcomecollection-workflow-export-bagit-stage/b13147195.tar.gz: 0-[end] / 1
```

This bug was introduced in https://github.com/wellcomecollection/storage-service/pull/448 – because we do a ranged GET request on the initial read of the file, the ContentLength in that response is the length of the range, not the entire file. The unpacker thinks every bag is a single byte long, so it thinks it can read the whole bag at once. At which point, boom, it reads an entire 10GB bag into memory and falls over.

Fix is to not make that ranged GET request, and avoid the "Some bytes not read" warning a different way.
