### ISSUE TITLE
Ingest uncatalogued accession 2535 (~180GB)

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4329]
For #4183

**Comment by alexwlchan** [comment]
Failed at the "Assign checksums and file sizes to objects" step:

```
updatesizeandchecksum_v0.0: INFO      2020-03-03 23:03:45,140  archivematica.mcp.client.updateSizeAndChecksum.call:171  Invoked as updatesizeandchecksum_v0.0 /var/archivematica/sharedDirectory/ --filePath /var/archivematica/sharedDirectory/currentlyProcessing/WT_2535-25cd7f1c-7246-4b84-a84c-64a0f8b30ef6/objects/Documentation Photos, Ben Gilbert for Wellcome_unedited selection/BTG170319144740.jpg --fileUUID 6a6275a3-4fc4-4d8d-9dfd-89ce33a3affa --eventIdentifierUUID b58e2314-64cc-4940-957f-d2f9d05f3cd7 --date 2020-03-03T23:02:54.996344+00:00.
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 182, in call
    args.event_uuid,
  File "/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 116, in main
    file_ = File.objects.get(uuid=file_uuid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 327, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

It’s got past this step before, so hoping this is just a transient thing?

**Comment by alexwlchan** [comment]
Ehmagerd it’s done! https://wellcome-ingest-inspector.glitch.me/ingests/d3e9474f-9680-4d83-b214-811afe07db25
