### ISSUE TITLE
Something goes wrong when rsync copies a large file around

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4341]
At some time in the small hours (according to CloudWatch it was 05:10:26, is Archivematica’s clock wrong?), we got an exception in the AM storage service logs by a failed rsync operation:

```
WARNING 2020-03-04 21:10:26 locations.models.space:space:move_rsync:600: Rsync failed with status -9: sending incremental file list
delta-transmission disabled for local transfer or --whole-file
WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9.tar.gz
rsync: [generator] write error: Broken pipe (32)
ERROR 2020-03-04 21:10:26 locations.models.async_manager:async_manager:wrapper:137: Task threw an error: Rsync failed with status -9: sending incremental file list
delta-transmission disabled for local transfer or --whole-file
WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9.tar.gz
rsync: [generator] write error: Broken pipe (32)
Traceback (most recent call last):
  File "/src/storage_service/locations/models/async_manager.py", line 134, in wrapper
    value = task_fn(*args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1031, in task
    self._store_bundle(bundle)
  File "/src/storage_service/locations/api/resources.py", line 994, in _store_bundle
    aip_subtype=aip_subtype,
  File "/src/storage_service/locations/models/package.py", line 775, in store_aip
    storage_effects, checksum = self._store_aip_to_uploaded(v, related_package_uuid)
  File "/src/storage_service/locations/models/package.py", line 924, in _store_aip_to_uploaded
    package=self,
  File "/src/storage_service/locations/models/space.py", line 362, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
  File "/src/storage_service/locations/models/local_filesystem.py", line 43, in move_to_storage_service
    return self.space.move_rsync(src_path, dest_path)
  File "/src/storage_service/locations/models/space.py", line 601, in move_rsync
    raise StorageException(s)
StorageException: Rsync failed with status -9: sending incremental file list
delta-transmission disabled for local transfer or --whole-file
WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9.tar.gz
rsync: [generator] write error: Broken pipe (32)
```

This blocks https://github.com/wellcomecollection/platform/issues/4329

What happens next is the storage service drops this particular request, and times out a waiting request from the MCP client.

This is the command it was running at the time:

```
rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/var/archivematica/sharedDirectory/currentlyProcessing/WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9/WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9.tar.gz', '/var/archivematica/sharedDirectory/wellcome-storage-service/fbfc/0c5b/c485/4745/ba43/a0a6/fc87/03e9/WT_2535-fbfc0c5b-c485-4745-ba43-a0a6fc8703e9.tar.gz']
```

WT 2535 is ~180GB in size, which might be why this issue occurred. If so, it bodes poorly for using Archivematica for our A/V workflow.

**Comment by alexwlchan** [comment]
Okay, but it timed out *before* this command failed – the MCP client request failed after ten minutes, whereas this took 17 minutes before it failed: https://archivematica.wellcomecollection.org/tasks/0244cef8-e24f-4a6f-bc84-418814400389/

**Comment by alexwlchan** [comment]
The issue occurs in the `move_rsync`, but for something this simple we can skip `mv` and use `os.rename()`, particularly as we know the Wellcome storage doesn't care about modification times or permissions like rsync does.

**Comment by alexwlchan** [comment]
Seems to be fixed.
