### ISSUE TITLE
Archivematica can't download transfers if the storage manifest is too big

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4367]
I *thought* I'd fixed this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 136, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/src/storage_service/locations/api/resources.py", line 1349, in download_request
    full_path = package.get_download_path(lockss_au_number)
  File "/src/storage_service/locations/models/package.py", line 269, in get_download_path
    full_path = self.fetch_local_path()
  File "/src/storage_service/locations/models/package.py", line 328, in fetch_local_path
    package=self,
  File "/src/storage_service/locations/models/space.py", line 362, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
  File "/src/storage_service/locations/models/wellcome.py", line 347, in move_to_storage_service
    stderr=subprocess.STDOUT
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 272, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 251, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 650, in __init__
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 619, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 1491, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long: 'python'
```

**Comment by alexwlchan** [comment]
We should probably fix this, but if we deploy the bag browser as the way to download bags it becomes much less important.

Parking until we do the workflow stuff. Required for https://github.com/wellcomecollection/platform/issues/4184

**Comment by alexwlchan** [comment]
Fix deployed.
