### ISSUE TITLE
Work out why "Assign file UUIDs and checksums" keeps failing in Archivematica

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4375]
A straggler from #4349; part of #4183

It fails consistently at the "Assign file UUIDs and checksums" step.

This affects:

* PPMIA/H/7/13
* PPSUL/B/1/7/4
* SAMED/2123/9
* SAPHY/Z/3/5/29a/2/3
* SATSY/1821/4

Stack trace from the MCP client:

```
archivematicaClient.py: INFO 2020-03-16 14:01:48,786 archivematica.mcp.client.updateSizeAndChecksum:call:249: Writing as updatesizeandchecksum_v0.0 /var/archivematica/sharedDirectory/ --filePath /var/archivematica/sharedDirectory/currentlyProcessing/SATSY_1821_4-83e5f2d1-9c3e-456a-a81d-a34cd930d193/objects/Disc 4/Section 64 Funding/Roadshow/names for Roadshow report --fileUUID 0d040ad3-162c
archivematicaClient.py: INFO      2020-03-16 14:01:48,786  archivematica.mcp.client.updateSizeAndChecksum:call:249:  Writing as updatesizeandchecksum_v0.0 /var/archivematica/sharedDirectory/ --filePath /var/archivematica/sharedDirectory/currentlyProcessing/SATSY_1821_4-83e5f2d1-9c3e-456a-a81d-a34cd930d193/objects/Disc 4/Section 64 Funding/Roadshow/names for Roadshow report --fileUUID 0d040ad3-162c-4bfb-9a83-9100b6f3a437 --eventIdentifierUUID 3a7e9b95-f3de-47e4-9bf5-de657667c026 --date 2020-03-16T14:01:48.404457+00:00.
archivematicaClient.py: ERROR 2020-03-16 14:01:49,111 archivematica.mcp.client:execute_command:268: Exception while processing task updatesizeandchecksum_v0.0: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
Traceback (most recent call last):
  File "/src/MCPClient/lib/archivematicaClient.py", line 214, in execute_command
    jobs = handle_batch_task(gearman_job, supported_modules)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 47, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPClient/lib/archivematicaClient.py", line 159, in handle_batch_task
    module.call(jobs)
  File "/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 262, in call
    kwargs=kwargs
  File "/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 140, in write_to_database
    updateSizeAndChecksum(file_uuid, file_path, date, event_uuid, **kwargs)
  File "/src/archivematicaCommon/lib/fileOperations.py", line 79, in updateSizeAndChecksum
    size=fileSize, checksum=checksum, checksumtype=checksumType
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 563, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
archivematicaClient.py: INFO 2020-03-16 14:01:49,114 archivematica.mcp.client:execute_command:208:
```

**Comment by alexwlchan** [comment]
I tweaked this code recently, so I wonder if I introduced a bug.

**Comment by alexwlchan** [comment]
I got into the RDS cluster, peering through logs now.

<details>
<summary>Output of <code>show engine innodb status;</code></summary>

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2020-03-17 12:49:32 2b151fe08700
*** (1) TRANSACTION:
TRANSACTION 109963511, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 14 lock struct(s), heap size 376, 15 row lock(s), undo log entries 25
MySQL thread id 810183, OS thread handle 0x2b13cd240700, query id 73371819 10.50.3.155 archivematica updating
UPDATE `Files` SET `checksum` = 'f3e7427549cff73d62de07cb70611e4b137194f0b03e0090c99353f8a5b605e9', `checksumType` = 'sha256', `fileSize` = 4026 WHERE `Files`.`fileUUID` = 'e1d27266-bcd6-4c1a-89c1-bedc4b3d115e'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 283 page no 21800 n bits 36 index `PRIMARY` of table `MCP`.`Files` trx id 109963511 lock_mode X locks rec but not gap waiting
Record lock, heap no 36 PHYSICAL RECORD: n_fields 16; compact format; info bits 0
 0: len=30; bufptr=0x2b14bafc3c00; hex= 65316432373236362d626364362d346331612d383963312d626564633462; asc e1d27266-bcd6-4c1a-89c1-bedc4b; (total 36 bytes);
 1: len=6; bufptr=0x2b14bafc3c24; hex= 0000068de549; asc      I;;
 2: len=7; bufptr=0x2b14bafc3c2a; hex= 3b000003da0566; asc ;     f;;
 3: len=30; bufptr=0x2b14bafc3c31; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 80 bytes);
 4: len=30; bufptr=0x2b14bafc3c81; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 80 bytes);
 5: len=8; bufptr=0x2b14bafc3cd1; hex= 6f726967696e616c; asc original;;
 6: len=0; bufptr=0x2b14bafc3cd9; hex= ; asc ;;
 7: len=30; bufptr=0x2b14bafc3cd9; hex= 663365373432373534396366663733643632646530376362373036313165; asc f3e7427549cff73d62de07cb70611e; (total 64 bytes);
 8: len=8; bufptr=0x2b14bafc3d19; hex= 8000000000000fba; asc         ;;
 9: len=0; bufptr=0x2b14bafc3d21; hex= ; asc ;;
 10: len=8; bufptr=0x2b14bafc3d21; hex= 99a5e2cc5d00d644; asc     ]  D;;
 11: SQL NULL;
 12: SQL NULL;
 13: len=30; bufptr=0x2b14bafc3d29; hex= 34383031303365322d333838382d343266302d626330372d643132363535; asc 480103e2-3888-42f0-bc07-d12655; (total 36 bytes);
 14: len=6; bufptr=0x2b14bafc3d4d; hex= 736861323536; asc sha256;;
 15: len=8; bufptr=0x2b14bafc3d53; hex= 99a5e2cc5d00d627; asc     ]  ';;

*** (2) TRANSACTION:
TRANSACTION 109962569, ACTIVE 1 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 81 lock struct(s), heap size 376, 150 row lock(s), undo log entries 365
MySQL thread id 810181, OS thread handle 0x2b13cd2c2700, query id 73372144 10.50.3.57 archivematica updating
UPDATE `Files` SET `checksum` = '30ca348e793ea59fa651038a28da43b85a498834fda53c001fce99537db4c205', `checksumType` = 'sha256', `fileSize` = 17522 WHERE `Files`.`fileUUID` = 'd5d6dac7-4fc4-43b6-9c0b-25b38fb22617'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 283 page no 21800 n bits 36 index `PRIMARY` of table `MCP`.`Files` trx id 109962569 lock_mode X locks rec but not gap
Record lock, heap no 36 PHYSICAL RECORD: n_fields 16; compact format; info bits 0
 0: len=30; bufptr=0x2b14bafc3c00; hex= 65316432373236362d626364362d346331612d383963312d626564633462; asc e1d27266-bcd6-4c1a-89c1-bedc4b; (total 36 bytes);
 1: len=6; bufptr=0x2b14bafc3c24; hex= 0000068de549; asc      I;;
 2: len=7; bufptr=0x2b14bafc3c2a; hex= 3b000003da0566; asc ;     f;;
 3: len=30; bufptr=0x2b14bafc3c31; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 80 bytes);
 4: len=30; bufptr=0x2b14bafc3c81; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 80 bytes);
 5: len=8; bufptr=0x2b14bafc3cd1; hex= 6f726967696e616c; asc original;;
 6: len=0; bufptr=0x2b14bafc3cd9; hex= ; asc ;;
 7: len=30; bufptr=0x2b14bafc3cd9; hex= 663365373432373534396366663733643632646530376362373036313165; asc f3e7427549cff73d62de07cb70611e; (total 64 bytes);
 8: len=8; bufptr=0x2b14bafc3d19; hex= 8000000000000fba; asc         ;;
 9: len=0; bufptr=0x2b14bafc3d21; hex= ; asc ;;
 10: len=8; bufptr=0x2b14bafc3d21; hex= 99a5e2cc5d00d644; asc     ]  D;;
 11: SQL NULL;
 12: SQL NULL;
 13: len=30; bufptr=0x2b14bafc3d29; hex= 34383031303365322d333838382d343266302d626330372d643132363535; asc 480103e2-3888-42f0-bc07-d12655; (total 36 bytes);
 14: len=6; bufptr=0x2b14bafc3d4d; hex= 736861323536; asc sha256;;
 15: len=8; bufptr=0x2b14bafc3d53; hex= 99a5e2cc5d00d627; asc     ]  ';;

[bitmap0 of 16 bytes in hex: 00 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00 ]
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 283 page no 28532 n bits 23 index `PRIMARY` of table `MCP`.`Files` trx id 109962569 lock_mode X locks rec but not gap waiting
Record lock, heap no 23 PHYSICAL RECORD: n_fields 16; compact format; info bits 0
 0: len=30; bufptr=0x2b12e7c1259d; hex= 64356436646163372d346663342d343362362d396330622d323562333866; asc d5d6dac7-4fc4-43b6-9c0b-25b38f; (total 36 bytes);
 1: len=6; bufptr=0x2b12e7c125c1; hex= 0000068de8f7; asc       ;;
 2: len=7; bufptr=0x2b12e7c125c7; hex= 38000003dd01c4; asc 8      ;;
 3: len=30; bufptr=0x2b12e7c125ce; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 56 bytes);
 4: len=30; bufptr=0x2b12e7c12606; hex= 257472616e736665724469726563746f7279256f626a656374732f446973; asc %transferDirectory%objects/Dis; (total 56 bytes);
 5: len=8; bufptr=0x2b12e7c1263e; hex= 6f726967696e616c; asc original;;
 6: len=0; bufptr=0x2b12e7c12646; hex= ; asc ;;
 7: len=30; bufptr=0x2b12e7c12646; hex= 333063613334386537393365613539666136353130333861323864613433; asc 30ca348e793ea59fa651038a28da43; (total 64 bytes);
 8: len=8; bufptr=0x2b12e7c12686; hex= 8000000000004472; asc       Dr;;
 9: len=0; bufptr=0x2b12e7c1268e; hex= ; asc ;;
 10: len=8; bufptr=0x2b12e7c1268e; hex= 99a5e2cc5d047f4a; asc     ]  J;;
 11: SQL NULL;
 12: SQL NULL;
 13: len=30; bufptr=0x2b12e7c12696; hex= 34383031303365322d333838382d343266302d626330372d643132363535; asc 480103e2-3888-42f0-bc07-d12655; (total 36 bytes);
 14: len=6; bufptr=0x2b12e7c126ba; hex= 736861323536; asc sha256;;
 15: len=8; bufptr=0x2b12e7c126c0; hex= 99a5e2cc5d047f26; asc     ]  &;;
```
</details>

**Comment by alexwlchan** [comment]
Hmm, they look like they're modifying different file UUIDs.

What if I just reboot the cluster? Will this problem magically go away? Let's try it and see.
