### ISSUE TITLE
IIIFBuilder special treatment for Chemist and Druggist

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4800]
Because it always has to be _special_.

We need to add the state management for building Chemist and Druggist.
In the new IIIF-Builder, it is possible to build any single issue of Chemist and Druggist on its own, without having to build the whole thing.

However, you won't be able to build the parent collection in a single pass - that needs to collect publication dates and other info from its descendants. This special logic is still to be ported.

**Comment by tomcrane** [comment]
What issue is this?
The problem here is consistent labeling and I'm not sure the old version was doing the right thing.

There are three numerical fields than can be used for issue number and possibly included in the label for an issue manifest.

These are:

**Title**

```
          <mods:titleInfo>
            <mods:title>2293</mods:title>
          </mods:titleInfo>
```
or

```
          <mods:titleInfo>
            <mods:title>-</mods:title>
          </mods:titleInfo>
```

**Part** with order attribute, containing **number**

```
          <mods:part order="2393" type="host">
            <mods:detail>
              <mods:number>1</mods:number>
            </mods:detail>
          </mods:part>
```
or (without number)

```
          <mods:part order="59" type="host">
            <mods:detail>
              <mods:number>-</mods:number>
            </mods:detail>
          </mods:part>
```

Where number is present, it's clearly the number of the issue within the volume, rather than an overall number across the publishing history.

However, the number used in Title and in Part->Order (I'll call this PartOrder in the spreadsheet later) are clearly something to do with the issue number across the whole history - but they aren't the same.

### Problems

Title is present in volumes 5-8 and volumes 56-274, but missing from the other volumes. So the majority have title, but about 1/5 do not.

PartOrder is not the same as title;  the first time we have both Title and PartOrder is volume 5; the first issue of this volume has Title "53" but PartNumber "57". By the time we get to volume 114 in 1931, we have Title 2681 and PartOrder 2795. After that, we get no more PartOrder constructs in the METS, so it's probably unsuitable.

There is the occasional double issue where the title is something like "4892/4893", but that's OK.

In the current live Chemist and Druggist, we assume that the METS title is the issue number, so from that we generate the IIIF Manifest labels like this:

> 3. July 1971 (issue 4765)

or

> 22/29. December 1973 (issue 4892/4893)

or

> 21 November 1896

The last one is an example of where there is no title in the METS. We can't use the partOrder instead, it would be misleading and in conflict with actual issues.

The problem is that different stretches of C&D have different available metadata.
We can just carry on doing what we're doing now, but this is an ideal opportunity to correct anything.

I have put what I think is all the relevant, usable metadata we have in the spreadsheet attached, so you can see what's up.

`NavDate` and `VolumeNavDate` are parsed dates, from the string values in the METS.

[c-and-d.xlsx](https://github.com/wellcomecollection/platform/files/6141996/c-and-d.xlsx)

**Comment by tomcrane** [comment]
Spreadsheet of C&D metadata:

[chemist-and-druggist.xlsx](https://github.com/wellcomecollection/platform/files/6142093/chemist-and-druggist.xlsx)

**Comment by tomcrane** [comment]
Progress:

https://iiif-test.wellcomecollection.org/presentation/b19974760
and an issue:
https://iiif-test.wellcomecollection.org/presentation/b19974760_7_0004

But problems:

- [ ] Volume collections are not being saved - e.g., https://iiif-test.wellcomecollection.org/presentation/b19974760_7
- [ ] Conversion to P2 is failing for b19974760 - see below for kibana stack trace. I think this is the requirement `p3Manifest.Items!` (note the `!`)... but why do we get here when converting these manifests as members of C&D and not manifests as members of a regular multi-vol collection?
- [ ] Conversion to P2 fails for manifests: "BuildLegacyIIIF called with non-IIIF3 BuildResult. Id: 'b19974760'"


Mar 16, 2021 @ 18:21:16.452 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.ConvertCollection(Collection p3Collection, DdsIdentifier identifier) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 126
-- | --

  | Mar 16, 2021 @ 18:21:16.452 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.Convert(StructureBase presentation, DdsIdentifier identifier, Int32 sequence) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 95

  | Mar 16, 2021 @ 18:21:16.451 | [18:21:16 ERR] Error converting bnumber 'b19974760' to IIIF2
  | Mar 16, 2021 @ 18:21:16.451 | System.ArgumentNullException: Value cannot be null. (Parameter 'source')

  | Mar 16, 2021 @ 18:21:16.451 | at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)

  | Mar 16, 2021 @ 18:21:16.451 | at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)

  | Mar 16, 2021 @ 18:21:16.451 | at Wellcome.Dds.Repositories.Presentation.V2.ConverterHelpers.IsBornDigital(Manifest p3Manifest) in /src/Wellcome.Dds.Repositories/Presentation/V2/ConverterHelpers.cs:line 195

  | Mar 16, 2021 @ 18:21:16.451 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.ConvertManifest(Manifest p3Manifest, DdsIdentifier identifier, Boolean rootResource, Nullable`1 sequence) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 136

  | Mar 16, 2021 @ 18:21:16.451 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.<>c__DisplayClass5_0.<ConvertCollection>b__0(Manifest m) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 124

  | Mar 16, 2021 @ 18:21:16.451 | at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()

  | Mar 16, 2021 @ 18:21:16.451 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.ConvertCollection(Collection p3Collection, DdsIdentifier identifier) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 122

  | Mar 16, 2021 @ 18:21:16.451 | at Wellcome.Dds.Repositories.Presentation.V2.PresentationConverter.<>c__DisplayClass5_0.<ConvertCollection>b__1(Collection c) in /src/Wellcome.Dds.Repositories/Presentation/V2/PresentationConverter.cs:line 128

  | Mar 16, 2021 @ 18:21:16.451 | at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()

  | Mar 16, 2021 @ 18:21:16.420 | [18:21:16 DBG] Building LegacyIIIF for Id 'b19974760'
