### ISSUE TITLE
Spurious errors in the ID minter logs

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4851]
If you look in the ID minter logs, you see errors like this:

```
08:45:30.718 [main-actor-system-akka.actor.default-dispatcher-140] ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: next on empty iterator
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.LinearSeqLike$$anon$1.next(LinearSeqLike.scala:50)
	at scala.collection.TraversableOnce$FlattenOps$$anon$2.next(TraversableOnce.scala:502)
	at uk.ac.wellcome.platform.id_minter.database.IdentifiersDao.readOnlySession(IdentifiersDao.scala:170)
	at uk.ac.wellcome.platform.id_minter.database.IdentifiersDao.lookupIds$default$2(IdentifiersDao.scala:29)
	at uk.ac.wellcome.platform.id_minter.steps.IdentifierGenerator.retrieveOrGenerateCanonicalIds(IdentifierGenerator.scala:25)
	at uk.ac.wellcome.platform.id_minter_works.services.IdMinterWorkerService.$anonfun$processJson$1(IdMinterWorkerService.scala:57)
	at scala.util.Success.flatMap(Try.scala:251)
	at uk.ac.wellcome.platform.id_minter_works.services.IdMinterWorkerService.processJson(IdMinterWorkerService.scala:55)
	at uk.ac.wellcome.platform.id_minter_works.services.IdMinterWorkerService.$anonfun$processMessage$1(IdMinterWorkerService.scala:51)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

They don't seem to affect works being minted – stuff still gets through okay – but it's a PITA if you're trying to follow the logs. We should find out where these are being thrown and fix them.

**Comment by alexwlchan** [comment]
Some discussion in Slack here: https://wellcome.slack.com/archives/CN56BRQ5B/p1603095998110000

And a tentative fix: https://github.com/wellcomecollection/catalogue/commit/1c49488ed862ed37db69c96d4a79c482a8cc147e

**Comment by alexwlchan** [comment]
Making the value lazy hasn't helped: https://logging.wellcomecollection.org/app/discover#/context/978cbc80-af0d-11ea-b454-cb894ee8b269/yTjmnHUBk9zFJ6cqdwO7?_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'978cbc80-af0d-11ea-b454-cb894ee8b269',key:service_name,negate:!f,params:(query:catalogue-20201023_work_id_minter),type:phrase),query:(match_phrase:(service_name:catalogue-20201023_work_id_minter)))))&_g=(filters:!())

We can tell that's the updated code, because the stack trace now contains:

```
	at uk.ac.wellcome.platform.id_minter.database.IdentifiersDao.readOnlySession(IdentifiersDao.scala:173)
```

which is the new line number.

**Comment by alexwlchan** [comment]
Fixed.
