### ISSUE TITLE
ID minter is dropping works when we do a reindex

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4957]
I've just run a reindex of just the Miro data into a clean index. Here are the stats:

<table>
<tr><td>Items in Miro source data VHS</td><td>421,608</td></tr>
<tr><td>Miro documents in ES index</td><td>421,140</td></tr>
</table>

At this point, the queues and DLQs are empty and all the tasks are scaled down. There shouldn't be any more work flowing through the pipeline – **so where are the other 468 items**?

I've attached a list of the missing IDs. At least one of them is present on the current site – see L0062945 – so we should fix this.

I'm going to try rerunning the index and see if the remaining items turn up.

**Comment by alexwlchan** [comment]
I've just realised I should check the intermediate indices!

```
GET /works-source-2021-01-08/_count
421,611 => 421,608 + 3 Sierra works in the mix
```

```
GET /works-identifier-2021-01-08/_count
421,142
```

So it sounds like the ID minter is dropping records.

**Comment by alexwlchan** [comment]
There's a bunch of failures in the ID minter logs of the form:

```
ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: next on empty iterator
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.LinearSeqLike$$anon$1.next(LinearSeqLike.scala:50)
	at scala.collection.TraversableOnce$FlattenOps$$anon$2.next(TraversableOnce.scala:502)
	at uk.ac.wellcome.platform.id_minter.database.IdentifiersDao.readOnlySession(IdentifiersDao.scala:173)
	at uk.ac.wellcome.platform.id_minter.database.IdentifiersDao.lookupIds$default$2(IdentifiersDao.scala:29)
	at uk.ac.wellcome.platform.id_minter.steps.IdentifierGenerator.retrieveOrGenerateCanonicalIds(IdentifierGenerator.scala:25)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.$anonfun$embedIds$1(IdMinterWorkerService.scala:62)
	at scala.util.Success.flatMap(Try.scala:251)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.embedIds(IdMinterWorkerService.scala:60)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.$anonfun$processMessage$1(IdMinterWorkerService.scala:54)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at uk.ac.wellcome.platform.id_minter.steps.IdentifierGenerator.retrieveOrGenerateCanonicalIds(IdentifierGenerator.scala:25)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.$anonfun$embedIds$1(IdMinterWorkerService.scala:62)
	at scala.util.Success.flatMap(Try.scala:251)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.embedIds(IdMinterWorkerService.scala:60)
	at uk.ac.wellcome.platform.id_minter.services.IdMinterWorkerService.$anonfun$processMessage$1(IdMinterWorkerService.scala:54)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

And because transformers no longer re-send works, these messages are now dropped.

**Comment by alexwlchan** [comment]
Sending one of these IDs back through the ID minter makes it appear in the index, so this transient ID minter error looks like the source of the problem. Investigating.

**Comment by alexwlchan** [comment]
Jamie points out this is the same stack trace as #4851. This error appeared 630 times in the ID minter logs in the last hour, which isn't the same number but seems close.

More discussion in Slack: https://wellcome.slack.com/archives/C3TQSF63C/p1610106306072900

**Comment by alexwlchan** [comment]
This seems to be fixed.
