### ISSUE TITLE
The works ingestor is failing with an out-of-memory exception

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4960]
e.g.

```
Uncaught error from thread [main-actor-system-akka.actor.default-dispatcher-7]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[main-actor-system]
java.lang.OutOfMemoryError: Java heap space
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:431)
	at com.sksamuel.elastic4s.json.XContentBuilder.autofield(XContentBuilder.scala:241)
	at com.sksamuel.elastic4s.json.SourceAsContentBuilder$.$anonfun$apply$1(SourceAsContentBuilder.scala:7)
	at com.sksamuel.elastic4s.json.SourceAsContentBuilder$$$Lambda$1401/0x0000000100970840.apply(Unknown Source)
	at scala.Function2.$anonfun$tupled$1(Function2.scala:53)
	at com.sksamuel.elastic4s.json.XContentBuilder.autofield(XContentBuilder.scala:241)
	at com.sksamuel.elastic4s.json.XContentBuilder.$anonfun$autovalue$2(XContentBuilder.scala:198)
	at com.sksamuel.elastic4s.json.XContentBuilder$$Lambda$1405/0x0000000100973840.apply(Unknown Source)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:394)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:721)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:721)
	at com.sksamuel.elastic4s.json.XContentBuilder.autovalue(XContentBuilder.scala:198)
	at com.sksamuel.elastic4s.json.XContentBuilder.$anonfun$autoarray$1(XContentBuilder.scala:208)
	at com.sksamuel.elastic4s.json.XContentBuilder$$Lambda$1404/0x0000000100973040.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.sksamuel.elastic4s.json.XContentBuilder.autoarray(XContentBuilder.scala:208)
	at com.sksamuel.elastic4s.json.XContentBuilder.autofield(XContentBuilder.scala:234)
	at com.sksamuel.elastic4s.json.XContentBuilder.$anonfun$autofield$1(XContentBuilder.scala:241)
	at com.sksamuel.elastic4s.json.XContentBuilder$$Lambda$1403/0x0000000100972040.apply(Unknown Source)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:431)
	at com.sksamuel.elastic4s.json.XContentBuilder.autofield(XContentBuilder.scala:241)
	at com.sksamuel.elastic4s.json.XContentBuilder.$anonfun$autofield$1(XContentBuilder.scala:241)
	at com.sksamuel.elastic4s.json.XContentBuilder$$Lambda$1403/0x0000000100972040.apply(Unknown Source)
	at io.circe.generic.extras.encoding.ConfiguredAsObjectEncoder$$anon$1.encodeObject(ConfiguredAsObjectEncoder.scala:69)
	at io.circe.generic.extras.encoding.ReprAsObjectEncoder.addDiscriminator(ReprAsObjectEncoder.scala:28)
	at io.circe.generic.extras.encoding.ReprAsObjectEncoder.addDiscriminator$(ReprAsObjectEncoder.scala:19)
	at uk.ac.wellcome.models.Implicits$anon$lazy$macro$11599$1$$anon$1671.addDiscriminator(Implicits.scala:269)
Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[main-actor-system]
```

This occurred when we reindexed the METS records.

Here's a list of the 40 IDs that landed on the DLQ:

```
aerbrxvp
agjbbp59
auvq6gyt
axbcyxhx
b9btfnvj
bfc9fu6b
cndq23tj
dedhfq6z
dyjbredb
e34mhmya
e4venrgn
f8zsvfvw
fpffmtg2
gdejna8f
hhwkwvge
jkqksdsg
mbgjt5fs
mftn8ccz
mwry6ery
n4egbzyh
nfagax42
nv66wbmn
nx9fqfy2
nz79gvpz
rcgey3v9
rhj5vwun
ryzvvbpq
s7e7tdqn
syqk24zj
uen7vkt7
uymttb54
vxxrgk4s
wngtaxjt
x3st8vzd
xbqax2mq
xv2pj9np
y7r25k2w
z6kfv6df
zmsjpxg5
zqpjawde
```

**Comment by alexwlchan** [comment]
This seems to be resolved in the latest reindex.
