### ISSUE TITLE
There are fewer works on the idminter index than on the transformers index after a reindex

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4966]
These messages should be routed to a DLQ, not dropped entirely.

**Comment by alicefuzier** [comment]
I don't know the cause of this but I'm not 100% convinced it's caused by database access. In today's reindex there was no contention and still it lost 28k messages

**Comment by alexwlchan** [comment]
I see errors like this in today's logs:

```
14:27:32.616 [main-actor-system-akka.actor.default-dispatcher-4] ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-118 [ACTIVE]
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-118 [ACTIVE]
	at com.sksamuel.elastic4s.http.JavaClient$$anon$1.onFailure(JavaClient.scala:69)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:644)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:399)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by alicefuzier** [comment]
So after investigation, I don't think is due to the id minter. I think the transformers fail to send some messages. What the trasnformers do is:
- read the source data to transform from s3
- transform the work
- read the es index to check if the work already exist
- if it does, check if the version is newer and the content is changed
  - if it is, ingest the work in es
  - send the work
- otherwise don't ingest or send it 

This is to avoid the nightly reharvest forcing the pipeline to redo expensive redundant work every night.
What I think is happening though, is sometimes there can be errors between ingesting and sending . If that happens the message is redriven by sqs. When the message is redriven, because the work was ingested, the condition not to send becoes true and the work is discarded
