### ISSUE TITLE
The image inferrer throws an out-of-memory error when we do a reindex

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5020]
And pretty reliably DLQs whatever else is going through the inference_manager at the time:

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:160)
	at java.base/java.lang.String.<init>(String.java:3214)
	at java.base/java.lang.String.<init>(String.java:276)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:421)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:296)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:243)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:243)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:251)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:243)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:251)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
Uncaught error from thread [main-actor-system-akka.actor.default-dispatcher-6]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[main-actor-system]
```

**Comment by alexwlchan** [comment]
I think it's somewhat deterministic – one of the images is the problem children – because redriving the DLQ sorts it out, just slowly.

**Comment by alexwlchan** [comment]
Here's a list of the 128 images that are currently failing in the image inferrer.

<details>

```
a5s54y42
ad79yjr8
am397a4n
ap55b5dg
asct4xb8
aty66egn
az3r5yg4
azzbvx8u
bcmkxydf
bp2gwjma
bsn4qpg5
bthbf7v6
chbcrhcd
cjpdjffm
ckk6b5fy
csaemwvx
ctxan6sx
d7af4pjw
d8xzbb32
djwmex29
dr6upw6f
dra4vcch
ds3acduj
dugs8hd4
dum9z3ms
e47w4adg
eby4zubt
ere55sgq
esx4e9xr
ezyvy92s
f6429nyr
fdvxcryt
ff55tgeu
fqqzc7xk
g5799y7c
g5w3zxh6
g8qda7g7
g9yruegm
gcjj9vgn
ghhh3wsa
gsw4x7ax
h6xzahc5
h7mcqyck
h94wgrc8
hj88y4zt
hn99cp23
jdfsxh9e
je9f47gs
js8kw5yp
jzcgtztp
k65cy4nw
k6muqk2e
kkkapbn8
kqymfym4
kr8v8p7h
mdsmtk3d
mmptswd3
mpsmbdtm
myda94wd
naw9zj8k
nb69yvf9
nf3agnzq
nmdd9fnu
np4ghyna
nqxacmm7
ns3uwpqx
ntq7vch5
pdjank8b
pjggkqjr
pqmcyy58
psvweuc5
pxjndu4e
pza8mpmf
q2gkfugu
q9p5xqrr
qchb4wg8
qg3rj6tt
qtmge4up
qu6dw4mk
qzavxyk5
r6t8rz4v
r7bbump4
r7zukess
rbkaz6zb
rcc7t46v
rcwn4vgq
rq4yu7m2
rq65b5h9
sa4r48uq
sghx3hf5
shn9nj8r
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
t8894apy
tefugbre
tfgjq9bj
tskrztpy
u4uvtszx
u8x5m584
unmq6xkn
v68ekwuw
vab5k6pc
vc67q5fy
vjw7m9zg
vnfwa7p2
vrfymcrm
vvh6mcf9
vw8h83be
vxgphz59
w3x36hmw
wcbg84je
wccxvysn
wwg7uqs3
x3x2rrcy
xmgvjhxm
xn4kywa2
xvhh5ubu
y3pfcr48
ydcy4s4a
yxrpagjp
zhpwdvry
zju2hnt9
zqgqc8sh
zt5jmfsn
ztzndvek
zxy4p9ur
```

</details>

**Comment by alexwlchan** [comment]
I've sent in ten images, let's see if they get through okay:

```
v68ekwuw
cjpdjffm
k65cy4nw
js8kw5yp
vw8h83be
g5w3zxh6
pjggkqjr
h6xzahc5
yxrpagjp
ztzndvek
ff55tgeu
```

**Comment by alexwlchan** [comment]
Down to 117 images.

<details>

```
117
a5s54y42
ad79yjr8
am397a4n
ap55b5dg
asct4xb8
aty66egn
az3r5yg4
azzbvx8u
bcmkxydf
bp2gwjma
bsn4qpg5
bthbf7v6
chbcrhcd
ckk6b5fy
csaemwvx
ctxan6sx
d7af4pjw
d8xzbb32
djwmex29
dr6upw6f
dra4vcch
ds3acduj
dugs8hd4
dum9z3ms
e47w4adg
eby4zubt
ere55sgq
esx4e9xr
ezyvy92s
f6429nyr
fdvxcryt
fqqzc7xk
g5799y7c
g8qda7g7
g9yruegm
gcjj9vgn
ghhh3wsa
gsw4x7ax
h7mcqyck
h94wgrc8
hj88y4zt
hn99cp23
jdfsxh9e
je9f47gs
jzcgtztp
k6muqk2e
kkkapbn8
kqymfym4
kr8v8p7h
mdsmtk3d
mmptswd3
mpsmbdtm
myda94wd
naw9zj8k
nb69yvf9
nf3agnzq
nmdd9fnu
np4ghyna
nqxacmm7
ns3uwpqx
ntq7vch5
pdjank8b
pqmcyy58
psvweuc5
pxjndu4e
pza8mpmf
q2gkfugu
q9p5xqrr
qchb4wg8
qg3rj6tt
qtmge4up
qu6dw4mk
qzavxyk5
r6t8rz4v
r7bbump4
r7zukess
rbkaz6zb
rcc7t46v
rcwn4vgq
rq4yu7m2
rq65b5h9
sa4r48uq
sghx3hf5
shn9nj8r
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
t8894apy
tefugbre
tfgjq9bj
tskrztpy
u4uvtszx
u8x5m584
unmq6xkn
vab5k6pc
vc67q5fy
vjw7m9zg
vnfwa7p2
vrfymcrm
vvh6mcf9
vxgphz59
w3x36hmw
wcbg84je
wccxvysn
wwg7uqs3
x3x2rrcy
xmgvjhxm
xn4kywa2
xvhh5ubu
y3pfcr48
ydcy4s4a
zhpwdvry
zju2hnt9
zqgqc8sh
zt5jmfsn
zxy4p9ur
```

</details>

**Comment by alexwlchan** [comment]
Sending in another twenty images.

```
t8894apy
nmdd9fnu
g8qda7g7
dr6upw6f
xn4kywa2
bcmkxydf
rq4yu7m2
ns3uwpqx
vnfwa7p2
wccxvysn
dugs8hd4
h94wgrc8
w3x36hmw
rcwn4vgq
azzbvx8u
ctxan6sx
shn9nj8r
unmq6xkn
psvweuc5
kkkapbn8
u4uvtszx
```

**Comment by alexwlchan** [comment]
Down to 96 images.

<details>

```
96
a5s54y42
ad79yjr8
am397a4n
ap55b5dg
asct4xb8
aty66egn
az3r5yg4
bp2gwjma
bsn4qpg5
bthbf7v6
chbcrhcd
ckk6b5fy
csaemwvx
d7af4pjw
d8xzbb32
djwmex29
dra4vcch
ds3acduj
dum9z3ms
e47w4adg
eby4zubt
ere55sgq
esx4e9xr
ezyvy92s
f6429nyr
fdvxcryt
fqqzc7xk
g5799y7c
g9yruegm
gcjj9vgn
ghhh3wsa
gsw4x7ax
h7mcqyck
hj88y4zt
hn99cp23
jdfsxh9e
je9f47gs
jzcgtztp
k6muqk2e
kqymfym4
kr8v8p7h
mdsmtk3d
mmptswd3
mpsmbdtm
myda94wd
naw9zj8k
nb69yvf9
nf3agnzq
np4ghyna
nqxacmm7
ntq7vch5
pdjank8b
pqmcyy58
pxjndu4e
pza8mpmf
q2gkfugu
q9p5xqrr
qchb4wg8
qg3rj6tt
qtmge4up
qu6dw4mk
qzavxyk5
r6t8rz4v
r7bbump4
r7zukess
rbkaz6zb
rcc7t46v
rq65b5h9
sa4r48uq
sghx3hf5
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
tefugbre
tfgjq9bj
tskrztpy
u8x5m584
vab5k6pc
vc67q5fy
vjw7m9zg
vrfymcrm
vvh6mcf9
vxgphz59
wcbg84je
wwg7uqs3
x3x2rrcy
xmgvjhxm
xvhh5ubu
y3pfcr48
ydcy4s4a
zhpwdvry
zju2hnt9
zqgqc8sh
zt5jmfsn
zxy4p9ur
```

</details>

**Comment by alexwlchan** [comment]
Sending in another twenty images.

```
a5s54y42
ap55b5dg
bsn4qpg5
vxgphz59
vrfymcrm
bp2gwjma
r7zukess
zt5jmfsn
d8xzbb32
esx4e9xr
wcbg84je
vjw7m9zg
rcc7t46v
ckk6b5fy
nb69yvf9
hn99cp23
tefugbre
q9p5xqrr
tskrztpy
zhpwdvry
aty66egn
```

**Comment by alexwlchan** [comment]
Down to 75 images.

<details>
```
75
ad79yjr8
am397a4n
asct4xb8
az3r5yg4
bthbf7v6
chbcrhcd
csaemwvx
d7af4pjw
djwmex29
dra4vcch
ds3acduj
dum9z3ms
e47w4adg
eby4zubt
ere55sgq
ezyvy92s
f6429nyr
fdvxcryt
fqqzc7xk
g5799y7c
g9yruegm
gcjj9vgn
ghhh3wsa
gsw4x7ax
h7mcqyck
hj88y4zt
jdfsxh9e
je9f47gs
jzcgtztp
k6muqk2e
kqymfym4
kr8v8p7h
mdsmtk3d
mmptswd3
mpsmbdtm
myda94wd
naw9zj8k
nf3agnzq
np4ghyna
nqxacmm7
ntq7vch5
pdjank8b
pqmcyy58
pxjndu4e
pza8mpmf
q2gkfugu
qchb4wg8
qg3rj6tt
qtmge4up
qu6dw4mk
qzavxyk5
r6t8rz4v
r7bbump4
rbkaz6zb
rq65b5h9
sa4r48uq
sghx3hf5
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
tfgjq9bj
u8x5m584
vab5k6pc
vc67q5fy
vvh6mcf9
wwg7uqs3
x3x2rrcy
xmgvjhxm
xvhh5ubu
y3pfcr48
ydcy4s4a
zju2hnt9
zqgqc8sh
zxy4p9ur
```
</details>

**Comment by alexwlchan** [comment]
Sending in another twenty images.

```
sj59zchr
pdjank8b
mdsmtk3d
pqmcyy58
nf3agnzq
qtmge4up
h7mcqyck
qzavxyk5
qchb4wg8
sghx3hf5
jzcgtztp
csaemwvx
stdqyh3x
chbcrhcd
g5799y7c
ds3acduj
f6429nyr
gcjj9vgn
y3pfcr48
nqxacmm7
xvhh5ubu
```

**Comment by alexwlchan** [comment]
Another 21 images in.

```
ydcy4s4a
bthbf7v6
hj88y4zt
t744wvxe
eby4zubt
pza8mpmf
djwmex29
wwg7uqs3
tfgjq9bj
dum9z3ms
t72z8c8t
zqgqc8sh
am397a4n
asct4xb8
g9yruegm
k6muqk2e
zxy4p9ur
rq65b5h9
je9f47gs
qg3rj6tt
fdvxcryt
```

**Comment by alexwlchan** [comment]
Ah, and suddenly I notice the following log:

```
Exception in ASGI application
Traceback (most recent call last):
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
    image = await get_image_from_url(query_url, size=100)
    "cannot identify image file %r" % (filename if filename else fp)
```

HMM.

**Comment by alexwlchan** [comment]
Here are the 100 images that failed in the 2020-02-17 reindex:

<details>

```
ad79yjr8
ap55b5dg
asct4xb8
aty66egn
az3r5yg4
azzbvx8u
bcmkxydf
bp2gwjma
bsn4qpg5
bthbf7v6
ckk6b5fy
csaemwvx
ctxan6sx
cxnjfy7t
d7af4pjw
d8xzbb32
djwmex29
dra4vcch
ds3acduj
dugs8hd4
dum9z3ms
e47w4adg
ezyvy92s
ff55tgeu
fhkh2gc4
g5799y7c
g5w3zxh6
g8qda7g7
g9yruegm
gcjj9vgn
gesfbusp
ghhh3wsa
gsw4x7ax
h6xzahc5
h7mcqyck
h94wgrc8
hctt6nub
hj88y4zt
hn99cp23
jdfsxh9e
jmbmu2jk
jzcgtztp
k65cy4nw
k68gbyak
k6muqk2e
kkkapbn8
kqymfym4
mdsmtk3d
mpsmbdtm
myda94wd
n76aqd7t
naw9zj8k
nb69yvf9
nf3agnzq
nmdd9fnu
np4ghyna
nqxacmm7
ntq7vch5
pjggkqjr
pqmcyy58
psvweuc5
pxjndu4e
pza8mpmf
q2gkfugu
q9p5xqrr
qchb4wg8
qu6dw4mk
r6t8rz4v
r7bbump4
r7zukess
rcc7t46v
rcwn4vgq
rq4yu7m2
rq65b5h9
sa4r48uq
sfqnhwww
sghx3hf5
shn9nj8r
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
tefugbre
tskrztpy
u6jrt29y
unmq6xkn
utuvxe5w
v68ekwuw
vab5k6pc
vc67q5fy
vnfwa7p2
vrfymcrm
vvh6mcf9
vw8h83be
w3x36hmw
wcbg84je
wwg7uqs3
x3x2rrcy
xejqxxy2
xmgvjhxm
xn4kywa2
xvhh5ubu
ydcy4s4a
yxrpagjp
zhpwdvry
zju2hnt9
zqgqc8sh
zt5jmfsn
ztzndvek
zxy4p9ur
```

</details>

**Comment by alexwlchan** [comment]
And here are the 99 images that failed in both reindexes:

<details>

```
ad79yjr8
ap55b5dg
asct4xb8
aty66egn
az3r5yg4
azzbvx8u
bcmkxydf
bp2gwjma
bsn4qpg5
bthbf7v6
ckk6b5fy
csaemwvx
ctxan6sx
d7af4pjw
d8xzbb32
djwmex29
dra4vcch
ds3acduj
dugs8hd4
dum9z3ms
e47w4adg
ezyvy92s
ff55tgeu
g5799y7c
g5w3zxh6
g8qda7g7
g9yruegm
gcjj9vgn
ghhh3wsa
gsw4x7ax
h6xzahc5
h7mcqyck
h94wgrc8
hj88y4zt
hn99cp23
jdfsxh9e
jzcgtztp
k65cy4nw
k6muqk2e
kkkapbn8
kqymfym4
mdsmtk3d
mpsmbdtm
myda94wd
naw9zj8k
nb69yvf9
nf3agnzq
nmdd9fnu
np4ghyna
nqxacmm7
ntq7vch5
pjggkqjr
pqmcyy58
psvweuc5
pxjndu4e
pza8mpmf
q2gkfugu
q9p5xqrr
qchb4wg8
qu6dw4mk
r6t8rz4v
r7bbump4
r7zukess
rcc7t46v
rcwn4vgq
rq4yu7m2
rq65b5h9
sa4r48uq
sghx3hf5
shn9nj8r
sj59zchr
stdqyh3x
t72z8c8t
t744wvxe
tefugbre
tskrztpy
unmq6xkn
v68ekwuw
vab5k6pc
vc67q5fy
vnfwa7p2
vrfymcrm
vvh6mcf9
vw8h83be
w3x36hmw
wcbg84je
wwg7uqs3
x3x2rrcy
xmgvjhxm
xn4kywa2
xvhh5ubu
ydcy4s4a
yxrpagjp
zhpwdvry
zju2hnt9
zqgqc8sh
zt5jmfsn
ztzndvek
zxy4p9ur
```

</details>

**Comment by alexwlchan** [comment]
We haven't seen this recently.
