### ISSUE TITLE
The images ingestor can throw a ContentTooLongException when retrieving images

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5038]
e.g.

```
ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: org.apache.http.ContentTooLongException: entity content is too long [130397743] for the configured buffer limit [104857600]
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: org.apache.http.ContentTooLongException: entity content is too long [130397743] for the configured buffer limit [104857600]
	at com.sksamuel.elastic4s.http.JavaClient$$anon$1.onFailure(JavaClient.scala:69)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:644)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:399)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:163)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:276)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This sounds like we're retrieving too many documents for the response: https://discuss.elastic.co/t/elasticsearch-rest-client-5-6-1-jar-org-apache-http-contenttoolongexception-entity-content-is-too-long-217056451-for-the-configured-buffer-limit-104857600/101387

**Comment by alexwlchan** [comment]
I'm going to try cranking down the batch size from 100 to 75.

**Comment by alexwlchan** [comment]
I had a brief look at adding some logic to handle this inside the Retriever, but it gets a bit tricky – to test this without queuing up 100MB+ of documents, you need to use RequestOptions and setHttpAsyncResponseConsumerFactory, and that's a pretty low-level setting that isn't exposed in the elastic4s client.

**Comment by alexwlchan** [comment]
This hasn't been an issue in recent reindexes; closing.
