### ISSUE TITLE
Errors in the logs from the Sierra bib merger

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5063]
We're seeing a whole pile of errors in the bib merger logs.

I spotted this while looking at https://github.com/wellcomecollection/platform/issues/5003

```
15:05:52.765 [main-actor-system-akka.actor.default-dispatcher-44] ERROR u.a.wellcome.messaging.sqs.SQSStream - Unrecognised failure while: Boxed Error
java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:406)
	at scala.concurrent.Promise$.fromTry(Promise.scala:142)
	at scala.concurrent.Promise$.failed(Promise.scala:128)
	at scala.concurrent.Future$.failed(Future.scala:624)
	at weco.catalogue.sierra_merger.services.Worker.process(Worker.scala:39)
	at weco.catalogue.sierra_merger.services.Worker.$anonfun$run$1(Worker.scala:65)
	at uk.ac.wellcome.messaging.sqs.SQSStream.$anonfun$foreach$2(SQSStream.scala:56)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1400)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Error: null
	at uk.ac.wellcome.storage.NoVersionExistsError$.apply$default$1(StorageError.scala:52)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashReadable.$anonfun$get$1(DynamoReadable.scala:78)
	at scala.util.Either.flatMap(Either.scala:341)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashReadable.get(DynamoReadable.scala:74)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashReadable.get$(DynamoReadable.scala:71)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashStore.get(DynamoStore.scala:31)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashStore.get(DynamoStore.scala:31)
	at weco.catalogue.source_model.store.SourceVHS.$anonfun$wrappedOp$1(SourceVHS.scala:20)
	at scala.util.Either.flatMap(Either.scala:341)
	at weco.catalogue.source_model.store.SourceVHS.wrappedOp(SourceVHS.scala:18)
	at weco.catalogue.source_model.store.SourceVHS.upsert(SourceVHS.scala:44)
	at weco.catalogue.sierra_merger.services.Updater.linkBib(Updater.scala:51)
	at weco.catalogue.sierra_merger.services.Updater.$anonfun$update$1(Updater.scala:33)
	at scala.collection.immutable.List.map(List.scala:293)
	at weco.catalogue.sierra_merger.services.Updater.update(Updater.scala:33)
	at weco.catalogue.sierra_merger.services.Worker.$anonfun$process$1(Worker.scala:32)
	at scala.util.Either.flatMap(Either.scala:341)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashReadable.get(DynamoReadable.scala:74)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashReadable.get$(DynamoReadable.scala:71)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashStore.get(DynamoStore.scala:31)
	at uk.ac.wellcome.storage.store.dynamo.DynamoHashStore.get(DynamoStore.scala:31)
	at weco.catalogue.source_model.store.SourceVHS.$anonfun$wrappedOp$1(SourceVHS.scala:20)
	at scala.util.Either.flatMap(Either.scala:341)
	at weco.catalogue.source_model.store.SourceVHS.wrappedOp(SourceVHS.scala:18)
	at weco.catalogue.source_model.store.SourceVHS.upsert(SourceVHS.scala:44)
	at weco.catalogue.sierra_merger.services.Updater.linkBib(Updater.scala:51)
	at weco.catalogue.sierra_merger.services.Updater.$anonfun$update$1(Updater.scala:33)
	at scala.collection.immutable.List.map(List.scala:293)
	at weco.catalogue.sierra_merger.services.Updater.update(Updater.scala:33)
	at weco.catalogue.sierra_merger.services.Worker.$anonfun$process$1(Worker.scala:32)
	at scala.util.Either.flatMap(Either.scala:341)
	at weco.catalogue.sierra_merger.services.Worker.process(Worker.scala:30)
	... 20 common frames omitted
```

This predates my changes for the Sierra adapter this week.

**Comment by alexwlchan** [comment]
I've identified the cause of this – patch incoming.

**Comment by alexwlchan** [comment]
To be safe, we should refetch all Calm and Sierra records from the start of last December.
