### ISSUE TITLE
Upgrade the buildkite agent

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/platform#5656]
We are currently using [version 5.7.2 ](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.7.2) of the Buildkite  Elastic CI stack:
https://github.com/wellcomecollection/buildkite-infrastructure/blob/main/terraform/buildkite.tf#L74

This is 15 months old  and relies on an older version of Docker, which [causes a segfault in Node](https://buildkite.com/wellcomecollection/wc-dot-org-end-to-end-tests/builds/2288#0185f324-45aa-48bd-b637-02f9f053bfc0)

Upgrade to the latest version.

**Comment by paul-butcher** [comment]
I attempted this recently, but the [batcher tests don't run](https://buildkite.com/wellcomecollection/catalogue-pipeline/builds/7598#0185f3c9-55c1-42f4-8283-c0f1f3aaf406) with any of the versions I tried (5.8.0, 5.10.0, 5.16.1).  Other tests seemed to run without issue.

**Comment by paul-butcher** [comment]
The most similar test suite (in terms of overall setup) appears to be the calm adapter, so I spent a while comparing them.

They both have an identical docker-compose, and the setup stuff in withWorkerService and withCalmAdapterWorkerService are pretty much the same, as is the general pattern of a test in the WorkerServiceTests (i.e. withWorkerService, sendNotificationToSQS, something happens)

I couldn't see any differences I thought relevant.  I started copying various less relevant looking settings between the two, to no avail.

**Comment by paul-butcher** [comment]
I set up debug logging, and noted a difference on startup. In batcher (which doesn't work):
```

11:13:27 [OpenSsl] DEBUG netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
--
  | 11:13:27 [Slf4jLogger] INFO  Slf4jLogger started
  | 11:13:27 [package$] DEBUG created test resource=[akka://default]
  | 11:13:27 [ExecutionInterceptorChain] DEBUG Creating an interceptor chain that will apply interceptors in the following order: [software.amazon.awssdk.core.internal.interceptor.HttpChecksumRequiredInterceptor@7e8295c2,
```

In calm adapter (which does):
```
10:52:52 [OpenSsl] DEBUG Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
  | java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
  | at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
  | at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:710)
 
```

So perhaps OpenSSL/netty-tcnative might be the difference, but I haven't found why this is different.

**Comment by paul-butcher** [comment]
I added storageLibrary to the batcher dependencies (to get netty-tcnative), and the same error messages arose as in the calm adapter, but it still fails.

**Comment by paul-butcher** [comment]
This is the log leading up to, and including the failure.

```


11:13:28 [ResourceLeakDetectorFactory] DEBUG Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@22229a21
--
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c, L:/127.0.0.1:47960 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [Recycler] DEBUG -Dio.netty.recycler.maxCapacityPerThread: 4096
  | 11:13:28 [Recycler] DEBUG -Dio.netty.recycler.ratio: 8
  | 11:13:28 [Recycler] DEBUG -Dio.netty.recycler.chunkSize: 32
  | 11:13:28 [Recycler] DEBUG -Dio.netty.recycler.blocking: false
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c, L:/127.0.0.1:47960 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c, L:/127.0.0.1:47960 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xa4ac762c, L:/127.0.0.1:47960 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de, L:/127.0.0.1:47964 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de, L:/127.0.0.1:47964 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de, L:/127.0.0.1:47964 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x9227b0de, L:/127.0.0.1:47964 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4, L:/127.0.0.1:47968 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4, L:/127.0.0.1:47968 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4, L:/127.0.0.1:47968 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x103165a4, L:/127.0.0.1:47968 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541, L:/127.0.0.1:47972 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541, L:/127.0.0.1:47972 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541, L:/127.0.0.1:47972 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xabae8541, L:/127.0.0.1:47972 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7, L:/127.0.0.1:47976 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7, L:/127.0.0.1:47976 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7, L:/127.0.0.1:47976 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x5c1933b7, L:/127.0.0.1:47976 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4, L:/127.0.0.1:47980 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4, L:/127.0.0.1:47980 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4, L:/127.0.0.1:47980 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc7dd8f4, L:/127.0.0.1:47980 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8, L:/127.0.0.1:47984 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8, L:/127.0.0.1:47984 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8, L:/127.0.0.1:47984 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x3104f7e8, L:/127.0.0.1:47984 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740, L:/127.0.0.1:47988 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740, L:/127.0.0.1:47988 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740, L:/127.0.0.1:47988 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0xdc1cf740, L:/127.0.0.1:47988 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca, L:/127.0.0.1:47992 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca, L:/127.0.0.1:47992 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca, L:/127.0.0.1:47992 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x052c6aca, L:/127.0.0.1:47992 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9] REGISTERED
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9] CONNECT: localhost/127.0.0.1:4566
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 - R:localhost/127.0.0.1:4566] ACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 - R:localhost/127.0.0.1:4566] READ COMPLETE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566] CLOSE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566] CLOSE
  | 11:13:28 [NettyRequestExecutor] DEBUG [Channel: [id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566]] Failed to initiate request to http://localhost:4566
  | java.io.IOException: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566], channelAge=PT0.010548S, requestCount=1)
  | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.configurePipeline(NettyRequestExecutor.java:233)
  | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$makeRequestListener$10(NettyRequestExecutor.java:181)
  | at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
  | at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
  | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566] INACTIVE
  | 11:13:28 [LoggingHandler] DEBUG [id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566] UNREGISTERED
  | 11:13:28 [request] DEBUG Retryable error detected. Will retry in 48ms. Request attempt number 2
  | software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566], channelAge=PT0.010548S, requestCount=1)
  | at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
  | at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:218)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:182)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
  | at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
  | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
  | at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
  | at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Caused by: java.io.IOException: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0x64411fd9, L:/127.0.0.1:47996 ! R:localhost/127.0.0.1:4566], channelAge=PT0.010548S, requestCount=1)
  | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.configurePipeline(NettyRequestExecutor.java:233)
  | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$makeRequestListener$10(NettyRequestExecutor.java:181)
  | at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
  | at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
  | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | ... 1 common frames omitted

```

This is what it looks like in the calm adapter, from ResourceLeakDetector (which is the same) on.



```
  | 10:52:54 [ResourceLeakDetectorFactory] DEBUG Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@173264a3
  | 10:52:54 [LoggingHandler] DEBUG [id: 0xc32e6a33] REGISTERED
  | 10:52:54 [LoggingHandler] DEBUG [id: 0xc32e6a33] CONNECT: localhost/127.0.0.1:4566
  | 10:52:54 [LoggingHandler] DEBUG [id: 0xc32e6a33, L:/127.0.0.1:55218 - R:localhost/127.0.0.1:4566] ACTIVE


  | 10:52:54 [LoggingHandler] DEBUG [id: 0xc32e6a33, L:/127.0.0.1:55218 - R:localhost/127.0.0.1:4566] WRITE: software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$StreamedRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
--
  | POST / HTTP/1.1
  | Host: localhost:4566
  | amz-sdk-invocation-id: 74bc8730-ec2e-1a25-76a0-6722e19a285e
  | amz-sdk-request: attempt=1; max=4
  | Authorization: AWS4-HMAC-SHA256 Credential=access/20230131/localhost/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=xxx
  | Content-Length: 62
  | Content-Type: application/x-www-form-urlencoded; charset=utf-8
  | User-Agent: aws-sdk-java/2.19.0 Linux/4.14.268-205.500.amzn2.x86_64 OpenJDK_64-Bit_Server_VM/11.0.15+10 Java/11.0.15 scala/2.12.8 vendor/Eclipse_Adoptium io/async http/NettyNio cfg/retry-mode/legacy
  | X-Amz-Date: 20230131T105253Z)
  | 10:52:54 [Recycler] DEBUG -Dio.netty.recycler.maxCapacityPerThread: 4096
  | 10:52:54 [Recycler] DEBUG -Dio.netty.recycler.ratio: 8
  | 10:52:54 [Recycler] DEBUG -Dio.netty.recycler.chunkSize: 32
  | 10:52:54 [Recycler] DEBUG -Dio.netty.recycler.blocking: false


```

The broken version lacks the `WRITE:` line, and jumps from `CONNECT:` to the Recycler settings

**Comment by paul-butcher** [comment]
I'm going to drop this back to 5.7.2 now and kick this into the long grass.

There is another workaround for the segfault issue, so this is not urgent, and I'll get on with what I was doing before.

**Comment by alexwlchan** [comment]
This is done.
